### ISSUE TITLE
`npm install` fails with error.

### ISSUE THREAD

**Issue by sbmueller** [chef-boneyard/devops-kungfu#266]
# Describe the problem
`sudo npm install` leads to error messages.

## Software Version
Master branch, Ubuntu 14.04.

## Replication Case
I'm using the Udacity DevOps course setup. This consists of a packer Ubuntu image, VirtualBox and Vagrant.

## Stacktrace
```
> node-sass@0.9.3 install /home/vagrant/devops-kung/node_modules/grunt-sass/node_modules/node-sass
> node build.js


/home/vagrant/devops-kung/node_modules/grunt-sass/node_modules/node-sass/node_modules/mocha/node_modules/debug/src/node.js:120
exports.inspectOpts = Object.keys(process.env).filter(key => {
                                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vagrant/devops-kung/node_modules/grunt-sass/node_modules/node-sass/node_modules/mocha/node_modules/debug/src/index.js:9:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! Linux 4.4.0-142-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.3 install: `node build.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the node-sass@0.9.3 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/devops-kung/npm-debug.log
```
Running the tests with `grunt -v` also yields errors.
```
/home/vagrant/devops-kung/node_modules/grunt-sass/tasks/sass.js:3
const util = require('util');
^^^^^
Loading "sass.js" tasks...ERROR
>> SyntaxError: Use of const in strict mode.
>>     at Module._compile (module.js:439:25)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at loadTask (/home/vagrant/devops-kung/node_modules/grunt/lib/grunt/task.js:323:10)
>>     at /home/vagrant/devops-kung/node_modules/grunt/lib/grunt/task.js:361:7
>>     at Array.forEach (native)
>>     at loadTasks (/home/vagrant/devops-kung/node_modules/grunt/lib/grunt/task.js:360:11)
```

## Possible Solution
Specify correct dependencies in `package.json`.

**Comment by Saburesh07** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
